<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Normora.Shared\Normora.Shared.csproj" />
    <ProjectReference Include="..\Normora.Infrastructure\Normora.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Normora.Modules.Auth\Normora.Modules.Auth.csproj" />
    <ProjectReference Include="..\Modules\Normora.Modules.Tenants\Normora.Modules.Tenants.csproj" />
    <ProjectReference Include="..\Modules\Normora.Modules.Users\Normora.Modules.Users.csproj" />
    <ProjectReference Include="..\Modules\Normora.Modules.Documents\Normora.Modules.Documents.csproj" />
  </ItemGroup>

</Project>
